apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment-web
  template:
    metadata:
      labels:
        app: deployment-web
    spec:
      containers:
        - name: web
          image: gcr.io/lab-6-451616/web:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: STORAGE_SVC
              value: "http://storage:80"
          livenessProbe:
            httpGet: 
              path: /phrase
              port: 3000
            periodSeconds: 2
            initialDelaySeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-web
spec:
  selector:
    app: deployment-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: loadBalancer